Called the domain once it is added to decrease consequent load time
argoapp-live/argo-api pull request #106
Opened 2021-08-24 17:28 UTC by Abhimanyu121

2021-09-02 08:46 UTC, rekpero commented
Hey @Abhimanyu121 can you run the linter/prettier and push the changes on this branch, seems like tests failed due to lint issue

2021-09-02 10:54 UTC, rekpero requested changes
Resolve the comments

2021-09-02 10:54 UTC, rekpero commented on src/components/Domain/service.ts
> +      axios.get(url);
I think we need to add `https://...` b/c domain is just the name without https

2021-09-02 10:54 UTC, rekpero commented on src/components/Domain/service.ts
> +      axios.get(url);
Tho check on the DB, if you can

2021-09-02 10:54 UTC, rekpero commented on src/components/Domain/index.ts
> +    DomainService.callDomain(result.domain.name);
@Abhimanyu121  this should be inside the if(...) block, I think.

2021-09-02 10:56 UTC, Abhimanyu121 commented on src/components/Domain/index.ts
> +    DomainService.callDomain(result.domain.name);
fixing

2021-09-08 15:32 UTC, rekpero requested changes
@Abhimanyu121 resolve the comment

2021-09-08 15:32 UTC, rekpero commented on src/components/Domain/service.ts
> +      axios.get(`https://${url}`);
@Abhimanyu121 try won't work on async call.
Do something like this
```suggestion
      axios.get(`https://${url}`).then(res => console.log("CALLING DOMAIN TO GENERATE CERTS")).catch(err => console.log);
```

2021-09-09 08:07 UTC, rekpero commented
@Abhimanyu121 prettier check failed, run it once more and commit it

2021-09-13 16:17 UTC, rekpero approved these changes

2021-09-13 16:17 UTC, merged