added support for various operations related to members.
argoapp-live/argo-api pull request #109
Opened 2021-09-02 09:11 UTC by Abhimanyu121

Sending deleting invites
Removing members from orgs
and many more minor changes

2021-09-03 16:13 UTC, rekpero requested changes
LGTM!!!
@akinovak do a review on this

2021-09-03 16:13 UTC, rekpero commented on src/routes/InvitationRouter.ts
> +router.post("/list", InvitationComponent.getInvites);
@Abhimanyu121 this should be a get call right?

2021-09-08 13:53 UTC, Abhimanyu121 commented on src/routes/InvitationRouter.ts
> +router.post("/list", InvitationComponent.getInvites);
yes fixing it

2021-09-13 16:28 UTC, rekpero approved these changes

2021-09-13 16:29 UTC, merged