Feature/subscribe deploy migration
argoapp-live/argo-api pull request #128
Opened 2021-11-02 15:10 UTC by dusanstanis

Base for subscription/bonus logic.

2021-11-09 18:50 UTC, rekpero requested changes
@dusanstanis code looks good, just a little bit of refactoring is needed on the interface side but good to merge.

2021-11-09 18:50 UTC, rekpero commented on test-producer.js
> +const { Producer } = require("sqs-producer");
@dusanstanis remove this file, and put it in the gitignore

2021-11-09 18:50 UTC, rekpero commented on test-consumer.js
> +const { Consumer } = require("sqs-consumer");
@dusanstanis remove this file, and put it in the gitignore

2021-11-09 18:50 UTC, rekpero commented on src/components/Subscription/model.ts
> +export interface ISubscription extends Document {
put this interface in `interfaces.ts`

2021-11-09 18:50 UTC, rekpero commented on src/components/SharedParameter/model.ts
> +export interface ISharedParameter extends Document {
move this to interfaces.ts file

2021-11-09 18:50 UTC, rekpero commented on src/components/SharedParameter/service.ts
> +const SharedParameterService = {
create an interface for this service and put it in the interfaces.ts

2021-11-09 18:50 UTC, rekpero commented on src/components/Subscription/service.ts
> +const SubscriptionService = {
create an interface for service and put it in interfaces.ts file

2021-11-09 18:50 UTC, rekpero commented on src/components/Bonus/service.ts
> +const BonusService = {
create an interface for this service and put it in interfaces.ts

2021-11-09 18:50 UTC, rekpero commented on src/components/Bonus/model.ts
> +export interface IBonus extends Document {
put this in interfaces.ts

2021-11-09 18:50 UTC, rekpero commented on src/components/SubscriptionPackage/model.ts
> +export interface ISubscriptionPackage extends Document {
put this in interfaces.ts file

2021-11-09 18:50 UTC, rekpero commented on src/components/SubscriptionPackage/service.ts
> +const SubscriptionPackageService = {
create an interface for this service and put it in interfaces.ts file

2021-11-09 19:06 UTC, rekpero commented
Also, @dusanstanis do run `num run prettier:write` before commiting

2021-11-10 12:00 UTC, akinovak commented on src/components/Deployment/dto-interfaces.ts
> +  payedViaSubscription: boolean;
paid?

2021-11-16 14:32 UTC, rekpero approved these changes

2021-11-17 11:16 UTC, merged