Feature/authorization
argoapp-live/argo-api pull request #151
Opened 2021-11-18 15:20 UTC by dusanstanis

Added authorization with roles and permissions in our system.

2021-11-27 15:24 UTC, rekpero requested changes
@dusanstanis PR lgtm!! please check the package json and revert the eslintConfig

2021-11-27 15:24 UTC, rekpero commented on package.json
> +    "extends": "eslint:recommended",
why is this changed? please remove the `eslintConfig`

2021-11-29 14:00 UTC, rekpero commented on src/routes/AuthRouter.ts
> +router.post("/fakeAuth", async (req, res) => {
why is this needed?

2021-11-29 14:01 UTC, rekpero commented on src/routes/DeploymentsRouter.ts
> +  grantAccess("deploymentAllowance"),
create these `deploymentAllowance` access types in an enum type and pass the enum here. it's much better than having string here

2021-11-29 14:02 UTC, rekpero commented on src/routes/RoleRouter.ts
> +  grantAccess("permissionManagementAllowance"),
same here, let's put these on a enum and use the enum to grant access to the API calls

2021-11-29 14:02 UTC, rekpero commented on src/routes/SubscriptionRouter.ts
> +  grantAccess("subscriptionAllowance"),
same here

2021-11-29 18:12 UTC, rekpero commented on package.json
> +    "extends": "eslint:recommended",
@nikoleta-vukajlovic @dusanstanis why is this still left

2021-11-29 18:25 UTC, rekpero approved these changes

2021-11-30 11:55 UTC, akinovak commented on src/components/Auth/service.ts
> +import RoleService from "../Role/service";
Should we mix different services in service.ts or add component with index.ts?

2021-11-30 14:23 UTC, akinovak approved these changes

2021-11-30 15:37 UTC, merged