Feature/bitbucket integration
argoapp-live/argo-api pull request #197
Opened 2021-12-07 11:34 UTC by nikoleta-vukajlovic

Fetching all workspaces for bitbucket, all repositories for workspace, all namspaces for gitlab, all repositories for namspace, all branches for repository for github and bitbucket

2021-12-10 16:35 UTC, rekpero requested changes
Please check the comments, and resolve them accordingly  @nikoleta-vukajlovic @dusanstanis

2021-12-10 16:35 UTC, rekpero commented on src/components/GitlabApp/service.ts
>      const projectInfo = await axios.get(
rename the variable to `namespaces`

2021-12-10 16:35 UTC, rekpero commented on src/components/GitlabApp/service.ts
> +    let getUserToken = await GitlabAppService.findByUserId(Types.ObjectId(id));
rename it to `gitUserToken`

2021-12-10 16:35 UTC, rekpero commented on src/components/GitlabApp/service.ts
> +    let getUserToken = await GitlabAppService.findByUserId(Types.ObjectId(id));
same here, rename it to `gitUserToken`

2021-12-10 16:35 UTC, rekpero commented on src/components/GitlabApp/service.ts
> +    let getUserToken = await GitlabAppService.findByUserId(Types.ObjectId(id));
same here: `gitUserToken`

2021-12-10 16:35 UTC, rekpero commented on src/components/Project/index.ts
> +      repositories: repositories,
```suggestion
      repositories,
```

2021-12-10 16:35 UTC, rekpero commented on src/components/Project/index.ts
> +    const repositories = await GitlabAppService.getNamespaces(
rename it to `namespaces`

2021-12-10 16:35 UTC, rekpero commented on src/components/Project/index.ts
> +      namespaces: repositories.data,
```suggestion
      namespaces,
```

2021-12-10 16:35 UTC, rekpero commented on src/components/Project/index.ts
> +      repositories: repositories,
```suggestion
      repositories,
```

2021-12-10 16:35 UTC, rekpero commented on src/templates/user-org-invite/ninatestapp.pem
> +-----BEGIN RSA PRIVATE KEY-----
what is this doing here, please remove this and put it in your gitignore

2021-12-10 17:17 UTC, rekpero requested changes
More comments @nikoleta-vukajlovic

2021-12-10 17:17 UTC, rekpero commented on src/routes/ProjectRouter.ts
> +  "/workspaces/:workspaceSlug",
rename it to `/bitbucket/app/:appId/repositories`

2021-12-10 17:17 UTC, rekpero commented on src/routes/ProjectRouter.ts
> +  "/namespaces/:namespaceId",
rename it to `/gitlab/app/:appId/repositories`

2021-12-13 15:16 UTC, rekpero requested changes
@nikoleta-vukajlovic some more refactor needed in this PR, please resolve them

2021-12-13 15:16 UTC, rekpero commented on src/components/GitRepository/index.ts
> +const axiosInstance = require("axios").default;
why do we need this, when `axios` is already imported

2021-12-13 15:16 UTC, rekpero commented on src/components/GitRepository/index.ts
> +  const getUserToken = await GithubAppService.findByUserId(id);
```suggestion
  const userToken = await GithubAppService.findByUserId(id);
```

2021-12-13 15:16 UTC, rekpero commented on src/components/GitRepository/index.ts
> +  const getUserToken = await GithubAppService.findByUserId(
```suggestion
  const userToken = await GithubAppService.findByUserId(
```

2021-12-13 15:16 UTC, rekpero commented on src/components/BitbucketApp/service.ts
> +    let getUserToken = await BitbucketAppService.findByUserId(
```suggestion
    let userToken = await BitbucketAppService.findByUserId(
```

2021-12-13 15:16 UTC, rekpero commented on src/components/BitbucketApp/service.ts
> +    let getUserToken = await BitbucketAppService.findByUserId(
```suggestion
    let userToken = await BitbucketAppService.findByUserId(
```

2021-12-13 15:16 UTC, rekpero commented on src/components/BitbucketApp/service.ts
> +    let getUserToken = await BitbucketAppService.findByUserId(
```suggestion
    let userToken = await BitbucketAppService.findByUserId(
```

2021-12-13 15:16 UTC, rekpero commented on src/components/BitbucketApp/service.ts
> +      repo_slug: repo_slug,
```suggestion
      repo_slug,
```

2021-12-13 15:16 UTC, rekpero commented on src/components/BitbucketApp/service.ts
> +      workspace: workspace,
```suggestion
      workspace,
```

2021-12-13 15:16 UTC, rekpero commented on src/components/BitbucketApp/service.ts
> +      getUserToken = await BitbucketAppService.refreshToken(Types.ObjectId(id));
```suggestion
      userToken = await BitbucketAppService.refreshToken(Types.ObjectId(id));
```

2021-12-13 15:16 UTC, rekpero commented on src/components/GitRepository/index.ts
> +  const getUserToken = await GitlabAppService.findByUserId(
```suggestion
  const userToken = await GitlabAppService.findByUserId(
```

2021-12-13 15:16 UTC, rekpero commented on src/components/GitlabApp/service.ts
>    async getRepositories(id: string): Promise<any> {
do we need this function anymore?

2021-12-13 15:16 UTC, rekpero commented on src/components/GitlabApp/service.ts
>    async getRepositories(id: string): Promise<any> {
Same for github and bitbucket components too. I think the endpoint is removed so remove this function or comment it out and put a deprecated comment on top of it.

2021-12-13 15:16 UTC, rekpero commented on src/components/BitbucketApp/service.ts
>    async getRepositories(id: string): Promise<any> {
same here, do we need this func anymore?

2021-12-13 15:33 UTC, nikoleta-vukajlovic commented on src/components/GitlabApp/service.ts
>    async getRepositories(id: string): Promise<any> {
will remove

2021-12-13 15:49 UTC, nikoleta-vukajlovic commented on src/components/GitRepository/index.ts
> +const axiosInstance = require("axios").default;
removed

2021-12-14 11:22 UTC, merged