Refactoring project component
argoapp-live/argo-api pull request #199
Opened 2021-12-07 11:52 UTC by nikoleta-vukajlovic

Endpoints from Project component that were related to git repositories are moved to GitRepository component

2021-12-10 16:25 UTC, rekpero requested changes
Please check the comments and answer all the questions asked @nikoleta-vukajlovic

2021-12-10 16:25 UTC, rekpero commented on src/routes/GitRepositoryRouter.ts
> +router.get("/bitbucket/app", GitRepositoryComponent.bitbucketApp);
What's the diff between `/bitbucket/app` & `/bitbucket/workspaces`? Both are fetching workspaces of a user, then what's different

2021-12-10 16:25 UTC, rekpero commented on src/routes/GitRepositoryRouter.ts
> +  "/installations/:installationId",
name this route like: `/github/app/:appId/repositories`

2021-12-10 16:25 UTC, rekpero commented on src/routes/GitRepositoryRouter.ts
> +  "/installations/repo/branch",
name this route as `/github/repo/branch`

2021-12-10 16:25 UTC, rekpero commented on src/routes/GitRepositoryRouter.ts
> +router.get("/bitbucket/app", GitRepositoryComponent.bitbucketApp);
What's the diff between `/bitbucket/app` & `/bitbucket/workspaces`? Both are fetching workspaces of a user, then what's different

2021-12-10 16:25 UTC, rekpero commented on src/routes/GitRepositoryRouter.ts
> +  "/bitbucket/repositories",
Here too, what's the diff b/w `/bitbucket/repositories` & `/workspaces/:workspaceSlug`? 
If `/bitbucket/repositories` just fetch all the repos of a user then remove it and just have the workspace repository only

2021-12-10 16:25 UTC, rekpero commented on src/routes/GitRepositoryRouter.ts
> +  "/workspaces/repo/branch",
name this route as `/bitbucket/repo/branch`

2021-12-10 16:25 UTC, rekpero commented on src/routes/GitRepositoryRouter.ts
> +router.get("/gitlab/app", GitRepositoryComponent.gitlabApp);
same here
What's the diff between `/gitlab/app` & `/gitlab/namespaces`? Both are fetching namespaces of a user, then what's different?

2021-12-10 16:25 UTC, rekpero commented on src/routes/GitRepositoryRouter.ts
> +  "/gitlab/repositories",
Here too, no need to have this route if it fetches all the repo of a user without considering namespace

2021-12-10 16:25 UTC, rekpero commented on src/routes/GitRepositoryRouter.ts
> +router.get("/namepsaces/repo/branch", GitRepositoryComponent.getGitlabBranches);
name this route as `/gitlab/repo/branch`
Also, why is `passportConfig.isAuthenticated` missing here, since Github and bitbucket have it, any reason not to put it here?

2021-12-10 16:25 UTC, rekpero commented on src/routes/index.ts
> +  app.use("/gitRepository", GitRepositoryRouter);
name it `git-meta`

2021-12-10 16:41 UTC, nikoleta-vukajlovic commented on src/routes/GitRepositoryRouter.ts
> +  GitRepositoryComponent.getBitbucketRepositories
getBitbucketRepositories is getting all repositories for passed user, getBitbucketWorkspaceRepositories is getting all repositories from passed user's workspace

2021-12-10 16:42 UTC, nikoleta-vukajlovic commented on src/routes/GitRepositoryRouter.ts
> +  GitRepositoryComponent.getGitlabRepositories
getGitlabRepositories is getting all repositories for passed user, getGitlabNamespaceRepositories is getting all repositories from passed user's namespace

2021-12-10 16:42 UTC, nikoleta-vukajlovic commented on src/routes/GitRepositoryRouter.ts
> +router.get("/bitbucket/app", GitRepositoryComponent.bitbucketApp);
Removed /bitbucket/app, these endpoints were doing the same thing

2021-12-13 08:23 UTC, nikoleta-vukajlovic commented on src/routes/GitRepositoryRouter.ts
> +router.get("/gitlab/app", GitRepositoryComponent.gitlabApp);
Will delete /gitlab/app

2021-12-13 08:24 UTC, nikoleta-vukajlovic commented on src/routes/GitRepositoryRouter.ts
> +  "/gitlab/repositories",
Will delete

2021-12-13 08:28 UTC, nikoleta-vukajlovic commented on src/routes/GitRepositoryRouter.ts
> +router.get("/namepsaces/repo/branch", GitRepositoryComponent.getGitlabBranches);
Put passportConfig.isAuthenticated here

2021-12-13 08:31 UTC, nikoleta-vukajlovic commented on src/routes/GitRepositoryRouter.ts
> +  "/gitlab/repositories",
Will delete /bitbucket/repositories also, since It also fetches all the repo without considering namespace

2021-12-13 12:41 UTC, nikoleta-vukajlovic commented on src/routes/GitRepositoryRouter.ts
> +router.get("/bitbucket/app", GitRepositoryComponent.bitbucketApp);
Will delete /bitbucket/app

2021-12-13 12:41 UTC, nikoleta-vukajlovic commented on src/routes/GitRepositoryRouter.ts
> +  "/bitbucket/repositories",
Will remove /bitbucket/repositories

2021-12-13 13:46 UTC, rekpero requested changes
@nikoleta-vukajlovic lgtm, just some nomenclature update, please resolve them and let @SingingApple know about these naming updates

2021-12-13 13:46 UTC, rekpero commented on src/routes/GitRepositoryRouter.ts
> +  "/bitbucket/workspaces",
rename this to `/bitbucket/app` to make it consistent with the github route

2021-12-13 13:46 UTC, rekpero commented on src/routes/GitRepositoryRouter.ts
> +  "/workspaces/:workspaceSlug",
rename this to `/bitbucket/app/:appId/repositories` for consistency

2021-12-13 13:46 UTC, rekpero commented on src/routes/GitRepositoryRouter.ts
> +  "/gitlab/namespaces",
same here, rename it to `/gitlab/app`

2021-12-13 13:46 UTC, rekpero commented on src/routes/GitRepositoryRouter.ts
> +  "/namespaces/:namespaceId",
here too, rename it to `/gitlab/app/:appId/repositories`

2021-12-13 13:46 UTC, rekpero commented on src/components/GitRepository/index.ts
> +export async function githubApp(req: Request, res: Response) {
rename this function to `getGithubOwners()`

2021-12-13 13:46 UTC, rekpero commented on src/components/GitRepository/index.ts
> +    installations: userInfo.data.installations,
```suggestion
    owners: userInfo.data.installations,
```

2021-12-13 13:46 UTC, rekpero commented on src/components/GitRepository/index.ts
> +export async function getInstallationRepos(
rename this to `getGithubOwnerRepositories()`

2021-12-13 13:46 UTC, rekpero commented on src/components/GitRepository/index.ts
> +export async function getBitbucketWorkspaces(
rename this function to `getBitbucketOwners()`

2021-12-13 13:46 UTC, rekpero commented on src/components/GitRepository/index.ts
> +      workspaces: workspaces.data.values,
```suggestion
      owners: workspaces.data.values,
```

2021-12-13 13:46 UTC, rekpero commented on src/components/GitRepository/index.ts
> +export async function getBitbucketWorkspaceRepositories(
```suggestion
export async function getBitbucketOwnerRepositories(
```

2021-12-13 13:46 UTC, rekpero commented on src/components/GitRepository/index.ts
> +      repositories: repositories,
```suggestion
      repositories,
```

2021-12-13 13:46 UTC, rekpero commented on src/components/GitRepository/index.ts
> +export async function getGitlabNamespaces(
```suggestion
export async function getGitlabOwners(
```

2021-12-13 13:46 UTC, rekpero commented on src/components/GitRepository/index.ts
> +      namespaces: repositories.data,
```suggestion
      owners: namespaces.data,
```

2021-12-13 13:46 UTC, rekpero commented on src/components/GitRepository/index.ts
> +    const repositories = await GitlabAppService.getNamespaces(
```suggestion
    const namespaces = await GitlabAppService.getNamespaces(
```

2021-12-13 13:46 UTC, rekpero commented on src/components/GitRepository/index.ts
> +export async function getGitlabNamespaceRepositories(
```suggestion
export async function getGitlabOwnerRepositories(
```

2021-12-13 13:46 UTC, rekpero commented on src/components/GitRepository/index.ts
> +      repositories: repositories,
```suggestion
      repositories,
```

2021-12-13 13:50 UTC, nikoleta-vukajlovic commented on src/routes/GitRepositoryRouter.ts
> +  "/workspaces/:workspaceSlug",
This was changed on the branch feature/bitbucketIntegration, but will change here also

2021-12-13 13:52 UTC, nikoleta-vukajlovic commented on src/routes/GitRepositoryRouter.ts
> +  "/namespaces/:namespaceId",
same for this one, will update here also

2021-12-13 15:07 UTC, merged