Pagination
argoapp-live/argo-api pull request #225
Opened 2022-01-10 13:06 UTC by nikoleta-vukajlovic

- fetch the number of repositories in an owner group
- paginated deployments are sorted by date of deployment descending

2022-01-11 07:41 UTC, rekpero requested changes

2022-01-11 07:41 UTC, rekpero commented on src/components/GitRepository/index.ts
> +      total: response.data.repositories.length,
this is not what I need, I want the total amount of repositories in a group without any pagination

2022-01-11 07:41 UTC, rekpero commented on src/components/GitRepository/index.ts
> +      total: repositories.data.values.length,
same here

2022-01-11 07:41 UTC, rekpero commented on src/components/GitRepository/index.ts
> +      total: repositories.length,
same here

2022-01-11 07:48 UTC, nikoleta-vukajlovic commented on src/components/GitRepository/index.ts
> +      total: response.data.repositories.length,
This will give you exactly that, if skip and limit are not passed, it returns all repositories in a group

2022-01-21 11:58 UTC, rekpero approved these changes

2022-01-21 11:58 UTC, merged