added support for having screenshots of website
argoapp-live/argo-api pull request #74
Opened 2021-07-12 09:03 UTC by Abhimanyu121

2021-07-12 15:48 UTC, akinovak commented on src/components/Deployment/service.ts
> +    async updateScreenshotUrl(deploymentId: string, screenshotUrl: IScreenshot): Promise<IDeployment> {
This should be called just screenshot instead of "screenshotUrl"

2021-07-12 16:24 UTC, Abhimanyu121 commented on src/components/Deployment/service.ts
> +    async updateScreenshotUrl(deploymentId: string, screenshotUrl: IScreenshot): Promise<IDeployment> {
Done

2021-07-12 16:45 UTC, akinovak commented on src/components/Deployment/service-interface.ts
> +    updateScreenshot(deploymentId: string, screenshotUrl: IScreenshot): Promise<IDeployment>;
Here also :)

2021-07-14 08:07 UTC, rekpero requested changes

2021-07-14 08:07 UTC, rekpero commented on src/config/env/index.ts
> +    key: string;
Rename it to `PRIVATE_KEY`, full caps

2021-07-14 08:07 UTC, rekpero commented on src/components/Deployment/service.ts
> +        const screenshoObj: IScreenshot = await nft.uploadScreenshotToArweave(url)
don't need to append with Obj, just name it `screenshot`

2021-07-14 08:07 UTC, rekpero commented on package.json
> +    "@argoapp/payment-js": "git+https://github.com/argoapp-live/argo-nft-js.git",
why is this here

2021-07-14 11:48 UTC, rekpero requested changes

2021-07-14 11:48 UTC, rekpero commented on src/components/Deployment/model.ts
> +    screenshotData: {
No need to append Data, it's self understandable

2021-07-14 11:48 UTC, rekpero commented on src/components/Deployment/model.ts
> +  screenshotData: any;
Here too, also create an interface rather than using `any`

2021-08-09 13:49 UTC, rekpero approved these changes

2021-08-09 13:52 UTC, merged